display error when calling -d or -g without ID
Signed-off-by: Florian Pritz <bluewind@server-speed.net>

diff --git a/fb.in b/fb.in
--- a/fb.in
+++ b/fb.in
@@ -155,7 +155,10 @@ TMPDIR="`mktemp -d "/tmp/fb.XXXXXX"`"
 trap "rm -rf '${TMPDIR}'" EXIT TERM
 
 if [ "$DELETE" ] || [ "$GET" ]; then
-	[ $# -eq 0 ] && exit 1;
+	if [ $# -eq 0 ]; then
+		echo "Error: no ID specified"
+		exit 1
+	fi
 	for i in "$@"; do
 		i=$(id_from_arg "$i")
 		if [ "$DELETE" ]; then
