check if the target file exists
Signed-off-by: Florian Pritz <bluewind@server-speed.net>

diff --git a/fb.in b/fb.in
--- a/fb.in
+++ b/fb.in
@@ -31,6 +31,13 @@ do_upload() {
 	file="$1"
 	basefilename="`basename -- "$file"`"
 	basedirname="`dirname -- "$file"`"
+
+	if [ ! -e "$file" ]; then
+		echo "Error: File \"$file\" doesn't exist" >&2
+		EXITCODE=1
+		return 1
+	fi
+
 	if [ -d "$file" ]; then
 		cd "$basedirname"
 		tar $TAROPTS -cf "$TMPDIR/$basefilename$TAREXT" -- "$basefilename"
