print an error if -t is used when operating on stdin
Signed-off-by: Florian Pritz <bluewind@server-speed.net>

diff --git a/fb.in b/fb.in
--- a/fb.in
+++ b/fb.in
@@ -168,6 +168,10 @@ if [ "$DELETE" ] || [ "$GET" ]; then
 		fi
 	done
 elif [ $# -eq 0 ]; then
+	if [ "$TAR" ]; then
+		echo "Error: -t is not supported when operating on stdin" >&2
+		exit 1
+	fi
 	read_stdin "$TMPDIR/stdin"
 	do_upload "$TMPDIR/stdin"
 else
